### ISSUE TITLE
UPDATE: IndexError: list index out of range

### ISSUE THREAD

**Issue by jaxk25** [jaxk25/Celebrity-Dogs#2]
On line _602_, the code `computer_cards.pop[cards]` isn't a valid statement. I think to use `list.pop()`, you have to be using Python 3.
It gives the following error:
```python
Traceback (most recent call last):
  File "H:\***\celebrity dogs game.py", line 1140, in <module>
    menu()#start the menu function
  File "H:\***\celebrity dogs game.py", line 14, in menu
    game()#start game function
  File "H:\***\celebrity dogs game.py", line 1120, in game
    computer_cards.pop[cards]
TypeError: 'builtin_function_or_method' object has no attribute '__getitem__'
```

**Comment by jaxk25** [comment]
Code has been updated but further errors are apparent:
```
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    game()
  File "H:\09-J.Greenacre\Desktop\GCSE\COMPUTER SCIENCE\python\celebrity dogs game.py", line 373, in game
    if player_cards[cards] == 'a':#if card == __ , do
IndexError: list index out of range
```

**Comment by jaxk25** [comment]
Code has been updated but there are further errors:
```
Traceback (most recent call last):
  File "H:\09-J.Greenacre\Desktop\GCSE\COMPUTER SCIENCE\python\celebrity dogs game.py", line 1177, in <module>
    menu()#start the menu function
  File "H:\09-J.Greenacre\Desktop\GCSE\COMPUTER SCIENCE\python\celebrity dogs game.py", line 14, in menu
    game()#start game function
  File "H:\09-J.Greenacre\Desktop\GCSE\COMPUTER SCIENCE\python\celebrity dogs game.py", line 1152, in game
    player_cards.pop(player_cards[cards])
TypeError: an integer is required
```

**Comment by jaxk25** [comment]
Code has been updated but the original issue has re-risen:
```
Traceback (most recent call last):
  File "H:\09-J.Greenacre\Desktop\GCSE\COMPUTER SCIENCE\python\celebrity dogs game.py", line 1187, in <module>
    menu()#start the menu function
  File "H:\09-J.Greenacre\Desktop\GCSE\COMPUTER SCIENCE\python\celebrity dogs game.py", line 14, in menu
    game()#start game function
  File "H:\09-J.Greenacre\Desktop\GCSE\COMPUTER SCIENCE\python\celebrity dogs game.py", line 862, in game
    if computer_cards[cards] == 'a':
IndexError: list index out of range
```

**Comment by jaxk25** [comment]
Code updated but the same error is occurring:
```
Traceback (most recent call last):
  File "H:\***\celebrity dogs game.py", line 1187, in <module>
    menu()#start the menu function
  File "H:\***\celebrity dogs game.py", line 14, in menu
    game()#start game function
  File "H:\***\celebrity dogs game.py", line 862, in game
    if computer_cards[cards] == 'a':
IndexError: list index out of range
```

**Comment by jaxk25** [comment]
High importance label added, @jaxk25 is struggling to solve it. All extra help would be helpful.
